SHELL := /bin/bash

ROOT := $(CURDIR)
BUILD := $(ROOT)/build
LINUX := $(ROOT)/vendor/linux
LINUX_BUILD := $(BUILD)/linux
EROFS_UTILS := $(ROOT)/vendor/erofs-utils
EROFS_UTILS_BUILD := $(BUILD)/erofs-utils

ARCH ?= x86_64
JOBS ?= $(shell nproc)
QEMU ?= qemu-system-x86_64
QEMU_ACCEL ?= tcg

KERNEL_IMAGE := $(LINUX_BUILD)/arch/x86/boot/bzImage
ROOTFS_DIR := $(BUILD)/rootfs
INIT_C := $(BUILD)/rootfs-init.c
INIT_BIN := $(ROOTFS_DIR)/init
INITRAMFS := $(BUILD)/initramfs.cpio.gz
EROFS_SRC := $(BUILD)/erofs-root
EROFS_IMG := $(BUILD)/rootfs.erofs
MKFS_EROFS := $(EROFS_UTILS_BUILD)/mkfs/mkfs.erofs
EROFS_DRIVE := -drive file=$(EROFS_IMG),if=virtio,format=raw,readonly=on
MALFORMED_QEMU_LOG ?= $(BUILD)/qemu-malformed.log
MALFORMED_QEMU_EXIT_CODE ?=

KERNEL_CMDLINE := console=ttyS0 earlyprintk=serial panic=-1
QEMU_ARGS := \
	-machine accel=$(QEMU_ACCEL) \
	-cpu max \
	-m 1024M \
	-smp 2 \
	-nographic \
	-no-reboot \
	-kernel $(KERNEL_IMAGE) \
	-initrd $(INITRAMFS) \
	-append "$(KERNEL_CMDLINE)"

.PHONY: all apt-deps deps-check kernel-config kernel erofs-utils erofs-utils-sanitized erofs-utils-safety initramfs erofs-image run smoke smoke-malformed smoke-dmesg test clean distclean help

all: kernel initramfs erofs-image

help:
	@printf '%s\n' \
		'Targets:' \
		'  make apt-deps       Install required Ubuntu packages with apt' \
		'  make deps-check     Check host tools needed by this repo' \
		'  make kernel-config  Generate .config and enable every EROFS option as built-in' \
		'  make kernel         Build the Linux bzImage' \
		'  make erofs-utils    Build local mkfs.erofs from vendor/erofs-utils' \
		'  make erofs-utils-sanitized  Build erofs-utils with ASAN/UBSAN instrumentation' \
		'  make erofs-utils-safety  Run mkfs/fsck/dump safety smoke over generated images' \
		'  make initramfs      Build a minimal initramfs that mounts the EROFS disk' \
		'  make erofs-image    Build build/rootfs.erofs' \
		'  make run            Build everything and boot it in QEMU' \
		'  make smoke          Boot QEMU with a timeout and verify mount plus traversal' \
		'  make smoke-malformed  Boot QEMU with a malformed image and verify safe rejection' \
		'  make smoke-dmesg      Boot QEMU and capture dmesg to build/qemu-dmesg.log' \
		'  make test           Run Rust unit and integration tests'

apt-deps:
	sudo apt update
	sudo apt install -y build-essential flex bison bc libssl-dev cpio gzip rsync \
		autoconf automake libtool libtool-bin pkg-config clang llvm qemu-system-x86 \
		dwarves libelf-dev liblz4-tool zstd uuid-dev liblz4-dev liblzma-dev zlib1g-dev libzstd-dev

deps-check:
	@missing=(); \
	for tool in gcc make flex bison bc openssl cpio gzip rsync autoconf automake libtoolize pkg-config $(QEMU); do \
		command -v $$tool >/dev/null 2>&1 || missing+=($$tool); \
	done; \
	if (($${#missing[@]})); then \
		echo "Missing required tools: $${missing[*]}"; \
		echo "Install them with: make apt-deps"; \
		exit 1; \
	fi

kernel-config: deps-check
	@if [ -f "$(LINUX)/.config" ] || [ -d "$(LINUX)/include/config" ]; then \
		echo "Cleaning previous in-tree kernel build..."; \
		$(MAKE) -C $(LINUX) ARCH=$(ARCH) mrproper; \
	fi
	@mkdir -p $(LINUX_BUILD)
	$(MAKE) -C $(LINUX) O=$(LINUX_BUILD) ARCH=$(ARCH) x86_64_defconfig
	$(ROOT)/scripts/enable-erofs-config.sh $(LINUX) $(LINUX_BUILD)

kernel: kernel-config
	$(MAKE) -C $(LINUX) O=$(LINUX_BUILD) ARCH=$(ARCH) -j$(JOBS) bzImage

erofs-utils: deps-check
	@if [ ! -x "$(MKFS_EROFS)" ]; then \
		if [ -f "$(EROFS_UTILS)/Makefile" ]; then \
			echo "Cleaning previous in-tree erofs-utils build..."; \
			$(MAKE) -C $(EROFS_UTILS) distclean 2>/dev/null || true; \
		fi; \
		cd $(EROFS_UTILS) && ./autogen.sh; \
		mkdir -p $(EROFS_UTILS_BUILD); \
		cd $(EROFS_UTILS_BUILD) && $(EROFS_UTILS)/configure --disable-fuse && $(MAKE) -j$(JOBS); \
	fi

erofs-utils-sanitized:
	$(ROOT)/scripts/build-erofs-utils-sanitized.sh

erofs-utils-safety: erofs-utils
	$(ROOT)/scripts/erofs-utils-safety-smoke.sh

$(INIT_C): scripts/rootfs-init.c
	@mkdir -p $(BUILD)
	cp $< $@

$(INIT_BIN): $(INIT_C)
	@rm -rf $(ROOTFS_DIR)
	@mkdir -p $(ROOTFS_DIR)/{dev,proc,sys,mnt/erofs,tmp}
	gcc -static -Os -Wall -Wextra -o $@ $<

initramfs: $(INIT_BIN)
	cd $(ROOTFS_DIR) && find . -print0 | cpio --null -ov --format=newc | gzip -9 > $(INITRAMFS)

erofs-image: erofs-utils
	@rm -rf $(EROFS_SRC)
	@mkdir -p $(EROFS_SRC)/etc $(EROFS_SRC)/demo
	printf 'hello from an EROFS-backed QEMU guest\n' > $(EROFS_SRC)/demo/hello.txt
	printf 'This read-only filesystem was generated by make erofs-image.\n' > $(EROFS_SRC)/etc/issue
	$(MKFS_EROFS) $(EROFS_IMG) $(EROFS_SRC)

run: all
	$(QEMU) $(QEMU_ARGS) $(EROFS_DRIVE)

smoke: all
	@mkdir -p $(BUILD)
	@set -o pipefail; \
	source scripts/kernel-replay-common.sh; \
	timeout 80s $(QEMU) $(QEMU_ARGS) $(EROFS_DRIVE) 2>&1 | tee $(BUILD)/qemu-smoke.log || rc=$$?; \
	qemu_rc="$${rc:-0}"; \
	if [ "$$qemu_rc" != 0 ] && [ "$$qemu_rc" != 124 ]; then exit "$$qemu_rc"; fi; \
	classify_dmesg "$(BUILD)/qemu-smoke.log" "$$qemu_rc"; \
	echo "$$REPLAY_RESULT: $$REPLAY_MSG"; \
	if [ "$$REPLAY_RESULT" != "ACCEPTED" ]; then exit 1; fi

# Boot with a malformed image and verify the kernel rejects it safely.
# This target requires MALFORMED_IMG to be set, e.g.:
#   make smoke-malformed MALFORMED_IMG=build/mutated.erofs
smoke-malformed: kernel initramfs
	@test -n "$(MALFORMED_IMG)" || { echo "Usage: make smoke-malformed MALFORMED_IMG=<path>"; exit 1; }
	@test -f "$(MALFORMED_IMG)" || { echo "Malformed image not found: $(MALFORMED_IMG)"; exit 1; }
	@mkdir -p "$(BUILD)" "$(dir $(MALFORMED_QEMU_LOG))"
	@set -o pipefail; \
	source scripts/kernel-replay-common.sh; \
	MALFORMED_DRIVE="-drive file=$(MALFORMED_IMG),if=virtio,format=raw,readonly=on"; \
	timeout 80s $(QEMU) $(QEMU_ARGS) $$MALFORMED_DRIVE 2>&1 | tee "$(MALFORMED_QEMU_LOG)" || rc=$$?; \
	qemu_rc="$${rc:-0}"; \
	if [ -n "$(MALFORMED_QEMU_EXIT_CODE)" ]; then \
		mkdir -p "$(dir $(MALFORMED_QEMU_EXIT_CODE))"; \
		printf '%s\n' "$$qemu_rc" > "$(MALFORMED_QEMU_EXIT_CODE)"; \
	fi; \
	if [ "$$qemu_rc" != 0 ] && [ "$$qemu_rc" != 124 ]; then exit "$$qemu_rc"; fi; \
	classify_dmesg "$(MALFORMED_QEMU_LOG)" "$$qemu_rc"; \
	echo "$$REPLAY_RESULT: $$REPLAY_MSG"; \
	if [ "$$REPLAY_RESULT" != "REJECTED" ]; then exit 1; fi

# Boot with the normal image and capture full dmesg for analysis.
smoke-dmesg: all
	@mkdir -p $(BUILD)
	@set -o pipefail; \
	$(QEMU) $(QEMU_ARGS) $(EROFS_DRIVE) 2>&1 | tee $(BUILD)/qemu-dmesg.log || rc=$$?; \
	if [ "$${rc:-0}" != 0 ] && [ "$${rc:-0}" != 124 ]; then exit "$${rc}"; fi; \
	grep -F "== erofs qemu booted ==" $(BUILD)/qemu-dmesg.log >/dev/null

test:
	cargo test

clean:
	rm -rf $(BUILD)

distclean: clean
	$(MAKE) -C $(LINUX) ARCH=$(ARCH) mrproper 2>/dev/null || true
	@if [ -f "$(EROFS_UTILS)/Makefile" ]; then $(MAKE) -C $(EROFS_UTILS) distclean 2>/dev/null || true; fi
